build japng debug

diff --git a/.github/workflows/build-japng.yml b/.github/workflows/build-japng.yml
--- a/.github/workflows/build-japng.yml
+++ b/.github/workflows/build-japng.yml
@@ -13,7 +13,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           repository: aellerton/japng
-          
+
       - name: Update Gradle wrapper
         run: |
           sed -i 's|distributionUrl=.*|distributionUrl=https\\://services.gradle.org/distributions/gradle-4.5-bin.zip|' gradle/wrapper/gradle-wrapper.properties
@@ -31,6 +31,14 @@ jobs:
       # Build and install japng to the local Maven repository without tests
       - name: Build and Install
         run: ./gradlew clean build publishToMavenLocal -x test
+
+      - name: Check if required Maven files exist
+        run: |
+          test -f ~/.m2/repository/japng/api/0.5.1/api-0.5.1.pom && echo "api-0.5.1.pom exists" || (echo "api-0.5.1.pom is missing" && exit 1)
+          test -f ~/.m2/repository/japng/api/0.5.1/api-0.5.1.jar && echo "api-0.5.1.jar exists" || (echo "api-0.5.1.jar is missing" && exit 1)
+
+      - name: Debug - List all files in home directory
+        run: find ~
 
       # Update Cache
       - name: Update Cache
